### ISSUE TITLE
auto testing error

### ISSUE THREAD

**Issue by arieling** [uber/sbnet#10]
I got the following error when I run `make test`, I am using GP100 and tensorflow1.2

======================================================================
ERROR: test_sparse_resblock_gradients (sparse_res_block_tests.SparseResBlockGradientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ais/gobi5/linghuan/sbnet/sbnet_tensorflow/benchmark/sparse_res_block_tests.py", line 267, in test_sparse_resblock_gradients
    xval, mask, bsize, strides, padding, data_format='NHWC')
  File "/ais/gobi5/linghuan/sbnet/sbnet_tensorflow/benchmark/sparse_res_block_tests.py", line 229, in _test_sparse_resblock_gradients
    yval = y.eval()
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 606, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3928, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
ResourceExhaustedError: OOM when allocating tensor with shape[1008726972,5,5,4]
         [[Node: SparseGather = SparseGather[T=DT_FLOAT, boffset=[-1, -1], bsize=[5, 5], bstride=[3, 3], transpose=false, _device="/job:localhost/replica:0/task:0/gpu:0"](Const, Variable_1/read/_69, Variable/read/_71)]]
         [[Node: SparseScatter/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_64_SparseScatter", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'SparseGather', defined at:
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/h/14/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/ais/gobi5/linghuan/sbnet/sbnet_tensorflow/benchmark/sparse_res_block_tests.py", line 267, in test_sparse_resblock_gradients
    xval, mask, bsize, strides, padding, data_format='NHWC')
  File "/ais/gobi5/linghuan/sbnet/sbnet_tensorflow/benchmark/sparse_res_block_tests.py", line 221, in _test_sparse_resblock_gradients
    use_var=False)
  File "/ais/gobi5/linghuan/sbnet/sbnet_tensorflow/benchmark/sparse_conv_lib.py", line 770, in sparse_res_block_bottleneck
    transpose=transpose)
  File "<string>", line 39, in sparse_gather
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1008726972,5,5,4]
         [[Node: SparseGather = SparseGather[T=DT_FLOAT, boffset=[-1, -1], bsize=[5, 5], bstride=[3, 3], transpose=false, _device="/job:localhost/replica:0/task:0/gpu:0"](Const, Variable_1/read/_69, Variable/read/_71)]]
         [[Node: SparseScatter/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_64_SparseScatter", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

======================================================================
FAIL: test_sparse_conv2d_with_mask_same (sparse_conv_tests.SparseConv2DCustomTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ais/gobi5/linghuan/sbnet/sbnet_tensorflow/benchmark/sparse_conv_tests.py", line 460, in test_sparse_conv2d_with_mask_same
    self._test_sparse_conv2d_custom_with_mask(mask, bsize, ksize, strides, padding, y_exp)
  File "/ais/gobi5/linghuan/sbnet/sbnet_tensorflow/benchmark/sparse_conv_tests.py", line 435, in _test_sparse_conv2d_custom_with_mask
    np.testing.assert_array_equal(y_act.reshape(y_exp.shape), y_exp)
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 855, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/u/linghuan/anaconda/envs/tf1.2/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 52.0%)
 x: array([[[[1.],
         [1.],
         [1.],...
 y: array([[[[1.],
         [6.],
         [6.],...

----------------------------------------------------------------------
Ran 40 tests in 186.952s

FAILED (failures=1, errors=1)
Makefile:14: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by andrei-pokrovsky** [comment]
Hi, we don't have a P100 here and otherwise can't reproduce this error.
Seeing a shape[1008726972,5,5,4] suggests that a large tensor is somehow coming out of reduce_mask so printing out the results of that op would help to narrow down the source of the problem.

So after line 206 in sparse_res_block_tests.py,

            with self.test_session() as sess:
                py_inds = sess.run([tf_ind])

 try printing out the results of py_inds to see if they look reasonable.
                py_inds = sess.run([tf_ind])

**Comment by andrei-pokrovsky** [comment]
It is possible that you need to add sm_60 build architecture to makefile.
