### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by dhingratul** [uber/sbnet#13]
======================================================================
ERROR: test_sparse_resblock_gradients (sparse_res_block_tests.SparseResBlockGradientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhingratul/OneDrive/Projects/sbnet/sbnet_tensorflow/benchmark/sparse_res_block_tests.py", line 273, in test_sparse_resblock_gradients
    xval, mask, bsize, strides, padding, data_format='NHWC', dynamic_size=dynamic_size)
  File "/home/dhingratul/OneDrive/Projects/sbnet/sbnet_tensorflow/benchmark/sparse_res_block_tests.py", line 211, in _test_sparse_resblock_gradients
    py_inds = sess.run([tf_ind])
  File "/home/dhingratul/.virtualenvs/sbnet/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/dhingratul/.virtualenvs/sbnet/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/dhingratul/.virtualenvs/sbnet/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 427, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/dhingratul/.virtualenvs/sbnet/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 245, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/dhingratul/.virtualenvs/sbnet/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 352, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/dhingratul/.virtualenvs/sbnet/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 245, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/dhingratul/.virtualenvs/sbnet/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 352, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/dhingratul/.virtualenvs/sbnet/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 253, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/home/dhingratul/.virtualenvs/sbnet/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 289, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument <tf.Tensor 'ReduceMask_1:0' shape=<unknown> dtype=int16> cannot be interpreted as a Tensor. (Tensor Tensor("ReduceMask_1:0", dtype=int16) is not an element of this graph.)

----------------------------------------------------------------------
Ran 40 tests in 389.501s

FAILED (errors=1)
Makefile:14: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by andrei-pokrovsky** [comment]
Hi, with our official supported config I can't reproduce this error. Can you please provide the following information:

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
TensorFlow installed from (source or binary):
TensorFlow version (use command below):
Python version:
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
Exact command to reproduce:

**Comment by dhingratul** [comment]
TensorFlow installed from (source or binary): pip
TensorFlow version (use command below): 1.8.0
Python version: 3.5
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:9/7.1
GPU model and memory: 1080ti/11gb X 2
Exact command to reproduce: make test
SbNet repo commit sha: 

commit 01e56ff95089acde6599087fc99f50075b070f1f
Author: Mengye Ren <mren3@uber.com>
Date:   Tue May 29 23:18:07 2018 -0400

**Comment by andrei-pokrovsky** [comment]
We are supporting Python 2.7 at this time. Have you tried with 2.7?

**Comment by dhingratul** [comment]
I will do that, I am assuming that is the reason that the make test fails, but i am still able to use the library successfully.
